
development:
  adapter: postgresql
  encoding: unicode
  database: sumbar-tourism_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: sumbar-tourism_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: sumbar-tourism_production
  pool: 5
  username: postgres
  password: password
