default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: sumbar-tourism_development

test:
  <<: *default
  database: sumbar-tourism_test

production:
  <<: *default
  database: sumbar-tourism_production
