settings: &settings
  facebook:
    alt: Facebook
    value: 'http://www.facebook.com/minang.tourism'
    editable: true
    deletable: false
    validations:
      presence: true
  twitter:
    alt: Twitter
    value: 'https://twitter.com/MinangTourism'
    editable: true
    deletable: false
    validations:
      presence: true
  phone:
    alt: Phone
    value: '081363152211'
    editable: true
    deletable: false
    validations:
      presence: true
  email:
    alt: Email
    value: 'minangtourism@gmail.com'
    editable: true
    deletable: false
    validations:
      presence: true
  address:
    alt: Address
    value: '-'
    editable: true
    deletable: false
    validations:
      presence: true
  
development:
  <<: *settings  
  
test:
  <<: *settings

production:
  <<: *settings
